wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.2
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719248357
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.12.4
      5: 0.17.2
      8:
      - 1
      - 5
      13: linux-x86_64
